[pronoun.data]
    placeholder = "Select prefered pronouns"
    id = 'mikro_pronoun_roles'
    min = 0
    max = -1
  [pronoun.data.message]
    description = "Select prefered pronoun roles"

[[pronoun.roles]]
    name = 'She/Her'
    description = 'Your prefered pronouns are She/Her'
    emoji = '🇸'
    role = 905260454992044163

[[pronoun.roles]]
    name = 'He/Him'
    description = 'Your prefered pronouns are He/Him'
    emoji = '🇭'
    role = 905260501884358676

[[pronoun.roles]]
    name = 'They/Them'
    description = 'Your prefered pronouns are They/Them'
    emoji = '🇹'
    role = 905260375803560027

[[pronoun.roles]]
    name = 'It/Its'
    description = 'Your prefered pronouns are It/Its'
    emoji = '🇮'
    role = 905261449859981355

[[pronoun.roles]]
    name = 'Any Pronouns'
    description = 'You are comfortable with any pronouns'
    emoji = '🇦'
    role = 905260550185971793

[[pronoun.roles]]
    name = 'Ask Me'
    description = 'You want people to ask you your pronouns'
    emoji = '🇵'
    role = 905260590895890463