[1076997550248296548]
    message = """
    **Please post your crash report**

    Go to your Minecraft folder (`~/minecraft`, wherever you installed your mods), go to the `crash-reports` folder, then send the most recent one here.
    """